# Generated by Django 3.1 on 2020-08-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, max_length=20)),
                ('l_name', models.CharField(blank=True, max_length=20)),
                ('ph_no', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
